language: php
dist: bionic
php:
  - 7.3
services:
  - docker
jobs:
  include:
    - if: branch = master
      env:
        - BUILD="latest"
    - if: NOT (branch = master)
      env:
        - BUILD="dev"
install:
  - yarn install --no-lockfile
  - yarn encore prod
  - docker-compose up -d
  - docker-compose exec paypal-playground composer install --prefer-source --no-interaction

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/yarn
    - node_modules

script:
  - docker-compose exec paypal-playground bin/phpunit
  - docker-compose exec paypal-playground composer install --no-dev
  - docker tag paypal-playground_paypal-playground paypal-playground:$BUILD
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push paypal-playground:$BUILD
