language: php
php:
  - 7.3

before_install:
  - nvm install 14.3

install:
  - composer install --prefer-source --no-interaction --no-dev
  - yarn install --no-lockfile --production
  - yarn encore prod

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/yarn
    - node_modules

script:
  - ./bin/phpunit
