language: php
dist: bionic
php:
  - 7.3
services:
  - docker

install:
  - yarn install --no-lockfile
  - yarn encore prod
  - docker-compose up -d
  - docker-compose exec paypal-playground-php-fpm composer install --prefer-source --no-interaction

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/yarn
    - node_modules

script:
  - docker-compose exec paypal-playground-php-fpm bin/phpunit
