language: php

php:
  - 7.3

install:

  - composer install --prefer-source --no-interaction --no-dev
  - npm config set registry http://npm.paypal.com/ --global
  - yarn install --production
  - yarn encore prod

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/yarn
    - node_modules

script:
  - ./bin/phpunit
