language: php

php:
  - 7.3

install:

  - composer install --prefer-source --no-interaction --dev
  - yarn install
  - yarn encore dev

cache:
  directories:
    - $HOME/.composer/cache/files

script:
  - phpunit
