language: php
php:
  - 7.3

before_install:
  - nvm install stable && nvm use stable

install:
  - composer install --prefer-source --no-interaction
  - yarn install --no-lockfile
  - yarn encore prod

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/yarn
    - node_modules

script:
  - ./bin/phpunit
