language: php
dist: bionic
php:
  - 7.3
services:
  - docker
jobs:
  include:
    - if: branch = master
      env:
        - BUILD="latest"
    - if: NOT (branch = master)
      env:
        - BUILD="dev"

install:
  - yarn install --no-lockfile
  - yarn encore prod
  - composer install --prefer-source --no-interaction

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/yarn
    - node_modules

script:
  - bin/phpunit
  - composer instal --no-dev
  - docker build . -t $DOCKER_USERNAME/paypal-playground:$BUILD

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag paypal-playground_paypal-playground $DOCKER_USERNAME/paypal-playground:$BUILD
  - docker push $DOCKER_USERNAME/paypal-playground
