version: "3.7"
services:
  paypal-playground:
    container_name: paypal-playground
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /var/www/html
    ports:
    - 8086:8080
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - "paypal.devoralive.docker:127.0.0.1"
